name: Deploy Portfolio Optimizer

on:
  push:
    branches: [ main ]
    paths:
      - 'tools/portfolio-optimizer/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/portfolio-optimizer

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Remove the cache configuration since it's causing issues
          
      - name: Install and Build
        run: |
          npm install
          npm run build
          
      - name: Prepare deployment
        run: |
          touch dist/.nojekyll
          cp dist/index.html dist/404.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tools/portfolio-optimizer/dist
          destination_dir: tools/portfolio-optimizer
          enable_jekyll: false
          force_orphan: true
